### ISSUE TITLE
Add documentation around using React components in a Solid application

### ISSUE THREAD

**Issue by spsaucier** [Sawtaytoes/reactjs-solidjs-bridge#1]
It sounds like this package can enable React Components to be used in a SolidJS application, but it wasn't clear from the documentation how to do so. Is that functionality currently possible, or am I missing something in the docs?

**Comment by Sawtaytoes** [comment]
That's correct.

Rendering Solid elements in React is fine.

Rendering React elements in Solid works, but I was trying to make it work with context and deeply-nested components. I never had time to finish that work.

Which one are you wanting in particular?

**Comment by spsaucier** [comment]
I've inherited a Solid app and a React Native app, but I'd like to share code between them, such as React hooks. These wouldn't have dependencies on Context APIs or anything too React-y.

Trying to weigh rewriting the MVP web app in React vs trying to work within Solid.

**Comment by Sawtaytoes** [comment]
Sharing React hooks with Solid components would be impossible. But you can share React components that include those hooks and have them pass props to SolidJS components. Would that work for you?

**Comment by spsaucier** [comment]
Sure, that could work, though for us it does take some of the usefulness out of sharing code, since React Native wouldn't be renderable to web without some modification. I'm thinking for this use-case it might be best to separate shared logic out into pure JS only (if we can) to share between the apps, without having to go through React after all.
