### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by StJohn3D** [Sawtaytoes/reactjs-solidjs-bridge#2]
This looks great, but few people are going to make use of it without an MIT license. Keep of the good work!

**Comment by Sawtaytoes** [comment]
Thank you so much for messaging!

I looked and noticed I have `"license": "MIT",`.

Where did you see there's no license?

**Comment by StJohn3D** [comment]
Oh I should have checked the package.json file. I'm personally in the habit of checking Git Repos to evaluate a new package before installing it. Typically, a GitHub repo will have a `LICENSE` file in the root and GitHub will detect it and show MIT or whatever on the right-hand side. E.g. 
![image](https://user-images.githubusercontent.com/7581439/149642129-5661621f-8cf7-452e-a131-5ee55432ad30.png)

**Comment by Sawtaytoes** [comment]
Fixed!
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/3948069/188932875-b3d107dc-28fb-4a22-8432-367b3ea81afc.png">
